services:

  hz1:
    image: hazelcast/hazelcast-enterprise:5.4.0-BETA-2
    environment:
      JAVA_OPTS: -Dhazelcast.config=/project/hazelcast.yaml
    volumes:
      - ".:/project"
    ports:
      - "5701:5701"
  hz2:
    image: hazelcast/hazelcast-enterprise:5.4.0-BETA-2
    environment:
      JAVA_OPTS: -Dhazelcast.config=/project/hazelcast.yaml
    volumes:
      - ".:/project"
    ports:
      - "5702:5702"

  hz3:
    image: hazelcast/hazelcast-enterprise:5.4.0-BETA-2
    environment:
      JAVA_OPTS: -Dhazelcast.config=/project/hazelcast.yaml
    volumes:
      - ".:/project"
    ports:
      - "5703:5703"


  mc:
    image: hazelcast/management-center:5.4.0-BETA-2
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hz1, hz2, hz3
    ports:
      - "8080:8080"
